### ISSUE TITLE
How to get all ligands' idx and download whole data

### ISSUE THREAD

**Issue by wen19shui** [MunibaFaiza/cheminformatics#1]
Dear Dr Muniba Faiza：

Hello, I am a student of chemical informatics, and I am now studying the content of ligands. I used your method and successfully downloaded the relevant ligand data in RCSB, which is great! Further, I hope to get the data of all ligands, but I don't have a proper way to get the numbers of all ligands. I tried to use the script to download from the ligand directory in ftp, but I failed. Do you have a way to know the number of all ligands in the website, or where to store these contents. Thank you.

**Comment by MunibaFaiza** [comment]
Hi Wen,
PDB does not display the exact number of ligands. Also, as you said it is difficult to download the ligands from the website. 
If you wish to get all ligands data from PDB, then you can download the PDB archive of all structures and then extract ligands from them. You can do it by separating the 'HETATM' coordinates from the PDB files. It will take a while but you will get all the ligands data which you can convert into any format.

**Comment by wen19shui** [comment]
Thank you for your advice. I will try~
